/**
 * Broadcast Routes
 *
 * GET  /api/broadcast/auth/status    — OAuth2 authorization state
 * POST /api/broadcast/auth/config    — set Client ID + Secret (saved to env/memory)
 * GET  /api/broadcast/auth/url       — get the Google consent URL
 * GET  /api/broadcast/auth/callback  — OAuth2 redirect handler (called by Google)
 * POST /api/broadcast/auth/revoke    — revoke authorization + delete saved tokens
 *
 * GET  /api/broadcast/status         — current broadcast lifecycle state
 * POST /api/broadcast/create         — create broadcast + stream, get RTMP URL
 * POST /api/broadcast/go-live        — transition broadcast → live
 * POST /api/broadcast/end            — transition broadcast → complete
 * GET  /api/broadcast/health         — YouTube stream health check
 * DELETE /api/broadcast              — delete current broadcast (cleanup)
 */

import { safeErrorMessage } from '../utils/error-response.js';
import { Router, type Request, type Response } from 'express';
import { youtubeAuthService } from '../services/youtube-auth.js';
import { youtubeBroadcastService } from '../services/youtube-broadcast.js';
import { rateLimit } from '../utils/rate-limit.js';

const router = Router();

// YouTube broadcast lifecycle is quota-expensive. Allow a healthy number of
// retries during a session start but block runaway loops (a misbehaving
// scheduler could otherwise burn the daily YouTube quota in minutes).
const broadcastWriteLimit = rateLimit({ keyPrefix: 'broadcast.write', max: 10, windowMs: 60_000 });

// ── Status ─────────────────────────────────────────────────────────────────────

router.get('/auth/status', async (_req: Request, res: Response) => {
  const channel = youtubeAuthService.isAuthorized
    ? await youtubeAuthService.fetchAuthorizedChannel().catch(() => null)
    : null;

  res.json({
    configured: youtubeAuthService.isConfigured,
    authorized: youtubeAuthService.isAuthorized,
    channel,   // { id, title, thumbnailUrl } or null
  });
});

// ── Configure credentials ──────────────────────────────────────────────────────

router.post('/auth/config', (req: Request, res: Response) => {
  const { clientId, clientSecret } = req.body as {
    clientId?: string;
    clientSecret?: string;
  };

  if (!clientId || !clientSecret) {
    res.status(400).json({ error: 'clientId and clientSecret are required' });
    return;
  }

  const port        = process.env.PORT || '3001';
  const redirectUri = `http://localhost:${port}/api/broadcast/auth/callback`;

  youtubeAuthService.configure(clientId, clientSecret, redirectUri);

  res.json({
    ok:      true,
    authUrl: youtubeAuthService.getAuthUrl(),
  });
});

// ── Get auth URL ───────────────────────────────────────────────────────────────

router.get('/auth/url', (_req: Request, res: Response) => {
  if (!youtubeAuthService.isConfigured) {
    res.status(400).json({ error: 'OAuth credentials not configured — POST /api/broadcast/auth/config first' });
    return;
  }
  res.json({ url: youtubeAuthService.getAuthUrl() });
});

// ── OAuth2 callback ────────────────────────────────────────────────────────────

router.get('/auth/callback', async (req: Request, res: Response) => {
  const { code, error, state } = req.query as { code?: string; error?: string; state?: string };

  if (error) {
    res.send(callbackPage(
      false,
      `Authorization denied: ${error}`,
      'You can close this tab and return to Claw DJ.'
    ));
    return;
  }

  if (!code) {
    res.status(400).send(callbackPage(false, 'No authorization code received.', ''));
    return;
  }

  // CSRF: `state` was generated by getAuthUrl() and must round-trip exactly.
  // Single-use, 5-minute expiry. Without this, an attacker can trick the
  // owner into completing an OAuth flow they didn't initiate, binding the
  // attacker's intended account on the owner's machine.
  if (!youtubeAuthService.verifyState(state)) {
    res.status(400).send(callbackPage(
      false,
      'Authorization state mismatch.',
      'This usually means the auth URL expired (5 min) or the flow was started from a different session. Restart auth from the dashboard.'
    ));
    return;
  }

  try {
    await youtubeAuthService.handleCallback(code);
    res.send(callbackPage(
      true,
      'YouTube account authorized',
      'Claw DJ can now create and manage live broadcasts on your channel. You can close this tab.'
    ));
  } catch (err) {
    console.error('[Broadcast] OAuth callback error:', err);
    res.status(500).send(callbackPage(
      false,
      'Authorization failed',
      safeErrorMessage(err)
    ));
  }
});

// ── Revoke ─────────────────────────────────────────────────────────────────────

router.post('/auth/revoke', async (_req: Request, res: Response) => {
  try {
    await youtubeAuthService.revoke();
    res.json({ ok: true });
  } catch (err) {
    console.error('[Broadcast] Revoke error:', err);
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

// ── Helpers ────────────────────────────────────────────────────────────────────

function callbackPage(success: boolean, heading: string, body: string): string {
  const color = success ? '#39ff6a' : '#ff3c64';
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Claw DJ — Authorization</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #030810;
      color: #c8d8f0;
      font-family: 'Courier New', monospace;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 40px;
    }
    .card {
      max-width: 480px;
      padding: 32px;
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 8px;
      background: #0a1628;
    }
    .icon { font-size: 32px; margin-bottom: 16px; }
    h2 { color: ${color}; font-size: 18px; margin-bottom: 12px; letter-spacing: 1px; }
    p { font-size: 13px; line-height: 1.6; color: rgba(200,216,240,0.7); }
    .label {
      display: inline-block;
      margin-top: 20px;
      font-size: 10px;
      letter-spacing: 2px;
      text-transform: uppercase;
      color: rgba(200,216,240,0.3);
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">${success ? '✓' : '✕'}</div>
    <h2>${heading}</h2>
    <p>${body}</p>
    <span class="label">Claw DJ — AI DJ System</span>
  </div>
</body>
</html>`;
}

// ── Broadcast lifecycle ─────────────────────────────────────────────────────────

router.get('/status', (_req: Request, res: Response) => {
  res.json(youtubeBroadcastService.info);
});

router.post('/create', broadcastWriteLimit, async (req: Request, res: Response) => {
  const { title, description, scheduledStartTime } = req.body as {
    title?: string;
    description?: string;
    scheduledStartTime?: string;
  };

  if (!title) {
    res.status(400).json({ error: 'title is required' });
    return;
  }

  if (!youtubeAuthService.isAuthorized) {
    res.status(401).json({ error: 'Not authorized — complete OAuth2 flow first' });
    return;
  }

  try {
    const info = await youtubeBroadcastService.createBroadcast(title, description, scheduledStartTime);
    res.json(info);
  } catch (err) {
    console.error('[Broadcast] Create error:', err);
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

router.post('/go-live', broadcastWriteLimit, async (_req: Request, res: Response) => {
  if (!youtubeAuthService.isAuthorized) {
    res.status(401).json({ error: 'Not authorized' });
    return;
  }

  try {
    await youtubeBroadcastService.goLive();
    res.json({ ok: true, status: 'live' });
  } catch (err) {
    console.error('[Broadcast] Go-live error:', err);
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

router.post('/end', async (_req: Request, res: Response) => {
  if (!youtubeAuthService.isAuthorized) {
    res.status(401).json({ error: 'Not authorized' });
    return;
  }

  try {
    await youtubeBroadcastService.endStream();
    res.json({ ok: true, status: 'complete' });
  } catch (err) {
    console.error('[Broadcast] End error:', err);
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

router.get('/health', async (_req: Request, res: Response) => {
  try {
    const health = await youtubeBroadcastService.getStreamHealth();
    res.json({ health });
  } catch (err) {
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

router.delete('/', async (_req: Request, res: Response) => {
  try {
    await youtubeBroadcastService.deleteBroadcast();
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: safeErrorMessage(err) });
  }
});

export default router;
